### PR TITLE
Minor configuration fixes

### PR DESCRIPTION
**Pull request by hakimio**
Multiple commits to make reviewing of the PR easier.
Changes in the PR:
- Use "production" config when building demo app by default
- Minor library build warning fix
- The old package lock didn't work for me with npm v7, so I regenerated it.
- Modified "paths" in tsconfig, so that changes made to the library would be applied to the demo app when just serving the demo with `ng serve`.
- Removed `npm link` since it was failing and doesn't seem to be needed anymore
- Fixed `Readme.md` casing which is most likely why it's missing from the [npm package](https://www.npmjs.com/package/ionic-header-parallax)

### CODE REVIEW

**Comment by RaschidJFR** [comment]
Thanks for the PR. All the changes are great. I just see an issue with the part of removing `ionic-header-parallax` from `package.json` as it would prevent the demo app from working as "standalone", thus can't be published as a live demo.  Any thoughts?

**Comment by hakimio** [comment]
You should still be able to build the production version of the demo without any issues because of the mapping in tsconfig and nothing should prevent you from being able to publish it to GitHub pages. I'll test again but I use this approach with my ngx-ui-tour library and it works for me.

**Comment by hakimio** [comment]
I have verified that the production version of the demo app works fine.

**Comment by hakimio** [comment]
Can't resolve the conflicts and since it's not very important PR, just closing it.

**Pull request closed without merging**
